name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Build Packages
        run: |
          sudo apt-get update
          sudo apt install build-essential qtbase5-dev qtmultimedia5-dev qtwebengine5-dev -y
      - name: make
        run: |
          mkdir build
          cd build
          cp ../package.yml ./
          cp ../src/Qqsp.desktop ./
          cp ../qqsp-recipe.yml ./
          qmake ../src/Qqsp.pro
          make
      - name: create icons
        run: |
          cd build
          sudo apt install imagemagick -y
          convert ../src/icons/qsp-logo-512.png -resize 16x16 16.png
          convert ../src/icons/qsp-logo-512.png -resize 48x48 48.png
          convert ../src/icons/qsp-logo-512.png -resize 64x64 64.png
          convert ../src/icons/qsp-logo-512.png -resize 128x128 128.png
          convert ../src/icons/qsp-logo-512.png -resize 256x256 256.png
      - name: Upload
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: Qqsp
          path: |
            build/Qqsp
            build/Qqsp.desktop
            build/*.png
            build/package.yml
            build/qqsp-recipe.yml

  package_appimage:
    needs: build_and_publish
    runs-on: ubuntu-latest
    env:
      artifact-id: ${{ needs.build_and_publish.outputs.artifact-id }}
    steps:
      - name: Install Build Packages
        run: |
          sudo apt-get update
          sudo apt install squashfs-tools -y
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ env.artifact-id }}
          path: artifact
      - name: Copy to root
        run: cp artifact/Qqsp/* ./
      - name: Build AppImage
        uses: Kidev/qt-appimage@v1
        with:
          install_folder: 'artifact/Qqsp/Qqsp'
          app_name: 'Qqsp'
          category: 'Games,Applications'
          icon: 'artifact/Qqsp/256.png'
          binary: 'Qqsp'  

#  package_appimage:
#    needs: build_and_publish
#    runs-on: ubuntu-latest
#    env:
#      artifact-id: ${{ needs.build_and_publish.outputs.artifact-id }}
#    steps:
#      - name: Install Build Packages
#        run: |
#          sudo apt-get update
#          sudo apt install squashfs-tools -y
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          artifact-ids: ${{ env.artifact-id }}
#          path: artifact
#      - name: Copy to root
#        run: cp artifact/Qqsp/* ./
#      - name: Create AppDir
#        run: |
#          mkdir -p AppDir/usr/bin
#
#          # Copy icons
#          for i in 16 48 64 128 256
#          do
#            mkdir -p AppDir/usr/share/icons/hicolor/"$i"x"$i"/apps
#            cp "$i".png AppDir/usr/share/icons/hicolor/"$i"x"$i"/apps/qsp.png
#          done
#
#          # Copy binary
#          cp Qqsp AppDir/usr/bin/Qqsp
#      - name: Build AppImage
#        uses: AppImageCrafters/build-appimage@master
#        with:
#          recipe: "./qqsp-recipe.yml"
#      - name: Upload Package
#        id: artifact-upload-step
#        uses: actions/upload-artifact@v4
#        with:
#          name: Qqsp-appimage-package
#          path: |
#            **/*.AppImage 

  package_deb:
    needs: build_and_publish
    runs-on: ubuntu-latest
    env:
      artifact-id: ${{ needs.build_and_publish.outputs.artifact-id }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ env.artifact-id }}
          path: artifact
      - name: Copy to root
        run: cp artifact/Qqsp/* ./
      - name: Create deb package
        uses: kentik/pkg@v1.0.0-rc8
        with:
          name: Qqsp
          version: 1.9
          arch: x86_64
          format: deb
          package: package.yml
      - name: Upload Package
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: Qqsp-deb-package
          path: |
            **/*.deb

  package_rpm:
    needs: build_and_publish
    runs-on: ubuntu-latest
    env:
      artifact-id: ${{ needs.build_and_publish.outputs.artifact-id }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ env.artifact-id }}
          path: artifact
      - name: Copy to root
        run: cp artifact/Qqsp/* ./
      - name: Create deb package
        uses: kentik/pkg@v1.0.0-rc8
        with:
          name: Qqsp
          version: 1.9
          arch: x86_64
          format: rpm
          package: package.yml
      - name: Upload Package
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: Qqsp-rpm-package
          path: |
            **/*.rpm

  release:
    if: github.ref_type == 'tag'
    needs:
      - package_deb
      - package_rpm
      - package_appimage
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifact
          pattern: Qqsp-*-package
          merge-multiple: true
      - run: ls -R artifact
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifact/Qqsp*

